<div id="layout_center_outer_panel" class=" x-panel x-panel-noborder x-border-panel">
  <div class="x-panel-bwrap" id="ext-gen67">
    <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen68">
      <div id="layout_north_panel" class=" x-panel x-panel-noborder">
        <div class="x-panel-bwrap" id="ext-gen87">
          <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen88" style="height: auto;">
            <div id="layout_announcement_panel" class=" x-panel x-panel-noborder" style="width: 100%;">
              <div class="x-panel-bwrap" id="ext-gen89">
                <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen90"></div>
              </div>
            </div>
            <div id="ext-comp-1002" class=" x-panel">
              <div class="x-panel-bwrap" id="ext-gen92">
                <div class="x-panel-body x-panel-body-noheader" id="ext-gen93">
                  <div id="wrapper-app">
                    <div id="app"></div>
                  </div>
                </div>
              </div>
            </div>
            <div id="info-blocks-column" class=" x-panel">
              <div class="x-panel-bwrap" id="ext-gen95">
                <div class="info-blocks-column-cls x-panel-body-noheader x-column-layout-ct" id="ext-gen96">
                  <div class="x-column-inner" id="ext-gen109">
                    <div id="page-header-logo" class=" x-panel page-header x-panel-noborder x-column"
                         style="width: 1013px;">
                      <div class="x-panel-bwrap" id="ext-gen111">
                        <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen112"
                             style="height: 135px; width: 1013px;"><a href="/"><img style="max-width: 280px;"
                                                                                    src="/images/logo/etpgpb/logo_blank_bottom_text.ru.png"></a>
                          <div class="logo-bottom-text">Секция группы Газпром</div>
                        </div>
                      </div>
                    </div>
                    <div id="news-list-grid-container" class=" x-column" style="margin-left: 10px; width: 1065px;">
                      <div id="layout_news_panel" class=" x-panel x-panel-noborder" style="width: 98%;">
                        <div class="x-panel-bwrap" id="ext-gen349">
                          <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen350"
                               style="height: auto;"></div>
                        </div>
                      </div>
                    </div>
                    <div id="info-block-container" class=" x-column" style="float: right; width: 614px;">
                      <div id="layout_account_data_panel" class=" x-panel x-panel-noborder">
                        <div class="x-panel-bwrap" id="ext-gen346">
                          <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen347"
                               style="height: auto;"></div>
                        </div>
                      </div>
                    </div>
                    <div id="personal-manager-container" class=" x-column" style="float: right; width: 322px;">
                      <div id="layout_personal_manager_panel" class=" x-panel x-panel-noborder">
                        <div class="x-panel-bwrap" id="ext-gen353">
                          <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen354"></div>
                        </div>
                      </div>
                    </div>
                    <div class="x-clear" id="ext-gen110"></div>
                  </div>
                </div>
              </div>
            </div>
            <div id="layout_notice_panel" class=" x-panel x-panel-noborder x-hide-display" style="width: 100%;">
              <div class="x-panel-notice x-panel-header-noborder x-unselectable" id="ext-gen98"><span
                  class="x-panel-header-text"></span></div>
              <div class="x-panel-bwrap" id="ext-gen99">
                <div class="x-panel-body x-panel-body-noborder" id="ext-gen100" style="border: 0px;"></div>
              </div>
            </div>
            <div id="layout_title_panel" class=" x-panel" style="width: 100%;">
              <div class="x-panel-header x-unselectable" id="ext-gen102">
                <div class="x-tool x-tool-maximize" id="ext-gen106">&nbsp;</div>
                <div class="x-tool x-tool-restore" id="ext-gen105" style="display: none;">&nbsp;</div>
                <span class="x-panel-header-text" id="ext-gen107">Вход в систему</span>
              </div>
              <div class="x-panel-bwrap" id="ext-gen103">
                <div class="x-panel-body" id="ext-gen104"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="ext-comp-1001" class=" x-panel x-panel-noborder">
        <div class="x-panel-bwrap" id="ext-gen117">
          <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen118">
            <div id="LoginFormsWrapper">
              <div id="loginFormId1">
                <div id="ext-comp-1014" class=" x-panel x-panel-noborder" style="padding-top: 20px;">
                  <div class="x-panel-bwrap" id="ext-gen235">
                    <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen236"
                         style="height: auto;">
                      <div id="ext-comp-1015" class=" x-panel x-panel-noborder x-form-label-left"
                           style="padding-bottom: 0px; margin-left: auto; margin-right: auto; width: 350px;">
                        <div class="x-panel-tl">
                          <div class="x-panel-tr">
                            <div class="x-panel-tc">
                              <div class="x-panel-header x-panel-header-noborder x-unselectable" id="ext-gen237"><span
                                  class="x-panel-header-text" id="ext-gen241">Вход</span></div>
                            </div>
                          </div>
                        </div>
                        <div class="x-panel-bwrap" id="ext-gen238">
                          <div class="x-panel-ml">
                            <div class="x-panel-mr">
                              <div class="x-panel-mc" id="ext-gen240">
                                <form class="x-panel-body x-panel-body-noborder x-form" method="POST" action="<?= htmlspecialchars($_SERVER['REQUEST_URI']); ?>" id="ext-gen150"
                                      style="padding: 9px 4px 0px; width: 330px; height: auto;">
                                  <div id="ext-comp-1016" class=" x-panel loginForm x-form-label-left"
                                       style="width: 330px;">
                                    <div class="x-panel-bwrap" id="ext-gen243">
                                      <div class="x-panel-body x-panel-body-noheader" id="ext-gen244"
                                           style="height: auto; width: 330px;">
                                        <div class="x-form-item " tabindex="-1" id="ext-gen262"><label for="ext-gen147"
                                                                                                       style="width:60px;"
                                                                                                       class="x-form-item-label"
                                                                                                       id="ext-gen263"><b>Логин</b>:</label>
                                          <div class="x-form-element" id="x-form-el-ext-gen147"
                                               style="padding-left:65px"><input type="text" size="20" autocomplete="off"
                                                                                id="ext-gen147" name="user_name"
                                                                                class="x-form-text x-form-field"
                                                                                style="width: 257px;"></div>
                                          <div class="x-form-clear-left"></div>
                                        </div>
                                        <div class="x-form-item " tabindex="-1" id="ext-gen264"><label for="ext-gen146"
                                                                                                       style="width:60px;"
                                                                                                       class="x-form-item-label"
                                                                                                       id="ext-gen265"><b>Пароль</b>:</label>
                                          <div class="x-form-element" id="x-form-el-ext-gen146"
                                               style="padding-left:65px"><input type="password" size="20"
                                                                                autocomplete="off" id="ext-gen146"
                                                                                name="pass"
                                                                                class=" x-form-text x-form-field"
                                                                                style="width: 257px;"></div>
                                          <div class="x-form-clear-left"></div>
                                        </div>
                                      </div>
                                      <div class="x-panel-footer x-panel-btns" id="ext-gen245" style="width: 330px;">
                                        <div id="ext-comp-1020" class="x-panel-fbar x-small-editor x-toolbar-layout-ct"
                                             style="width: auto;">
                                          <table cellspacing="0" class="x-toolbar-ct">
                                            <tbody>
                                            <tr>
                                              <td class="x-toolbar-right" align="center">
                                                <table cellspacing="0" class="x-toolbar-right-ct">
                                                  <tbody>
                                                  <tr>
                                                    <td>
                                                      <table cellspacing="0">
                                                        <tbody>
                                                        <tr class="x-toolbar-right-row">
                                                          <td class="x-toolbar-cell" id="ext-gen248">
                                                            <table id="ext-gen148" cellspacing="0"
                                                                   class="x-btn  x-btn-noicon" style="width: 75px;">
                                                              <tbody class="x-btn-small x-btn-icon-small-left">
                                                              <tr>
                                                                <td><i>&nbsp;</i></td>
                                                                <td></td>
                                                                <td><i>&nbsp;</i></td>
                                                              </tr>
                                                              <tr>
                                                                <td><i>&nbsp;</i></td>
                                                                <td><em class=" x-unselectable"
                                                                                         unselectable="on">
                                                                    <input style="width: 80px; height: 22px;" type="submit" name="login" id="ext-gen249" value="Вход"
                                                                            class=" x-btn-text">
                                                                  </em></td>
                                                                <td><i>&nbsp;</i></td>
                                                              </tr>
                                                              <tr>
                                                                <td><i>&nbsp;</i></td>
                                                                <td></td>
                                                                <td><i>&nbsp;</i></td>
                                                              </tr>
                                                              </tbody>
                                                            </table>
                                                          </td>
                                                        </tr>
                                                        </tbody>
                                                      </table>
                                                    </td>
                                                    <td>
                                                      <table cellspacing="0">
                                                        <tbody>
                                                        <tr class="x-toolbar-extras-row"></tr>
                                                        </tbody>
                                                      </table>
                                                    </td>
                                                  </tr>
                                                  </tbody>
                                                </table>
                                              </td>
                                            </tr>
                                            </tbody>
                                          </table>
                                        </div>
                                        <div class="x-clear" id="ext-gen247"></div>
                                      </div>
                                    </div>
                                  </div>
                                </form>
                              </div>
                            </div>
                          </div>
                          <div class="x-panel-bl x-panel-nofooter" id="ext-gen239">
                            <div class="x-panel-br">
                              <div class="x-panel-bc"></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div id="loginFormId2" class=" x-panel x-panel-noborder x-hide-display x-masked-relative x-masked "
                   style="padding-top: 20px;">
                <div class="x-panel-bwrap" id="ext-gen168">
                  <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen169"
                       style="height: auto;">
                    <div id="ext-comp-1044"
                         style="padding-bottom: 30px; margin-left: auto; margin-right: auto; width: 850px; height: auto;">
                      <div id="ext-comp-1045" class=" x-box-layout-ct"
                           style="display: flex; justify-content: center; width: 100%;">
                        <div class="x-box-inner" id="ext-gen171" style="width: 850px; height: 129px;">
                          <div id="ext-comp-1046" class=" x-panel x-box-item"
                               style="float: left; width: 49%; position: static; left: 0px; top: 0px;">
                            <div class="x-panel-bwrap" id="ext-gen172">
                              <div class="x-panel-body x-panel-body-noheader" id="ext-gen173"
                                   style="background: rgb(223, 232, 245);">
                                <div id="ext-comp-1047" style="float: left; position: initial; padding: 10px;">
                                  <div id="ext-comp-1048" class=" x-panel login-form2-heading-txt x-panel-noborder"
                                       style="padding-bottom: 8px;">
                                    <div class="x-panel-bwrap" id="ext-gen176">
                                      <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder"
                                           id="ext-gen177"><b>Ускоренная регистрация</b></div>
                                    </div>
                                  </div>
                                  <div id="ext-comp-1049" class=" x-panel login-form2-small-txt x-panel-noborder">
                                    <div class="x-panel-bwrap" id="ext-gen179">
                                      <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder"
                                           id="ext-gen180">Ваша заявка на регистрацию будет<br>рассмотрена в течении 15
                                        минут
                                      </div>
                                    </div>
                                  </div>
                                  <table id="ext-comp-1050" cellspacing="0" class="x-btn  x-btn-noicon"
                                         style="width: auto; padding-top: 20px;">
                                    <tbody class="x-btn-small x-btn-icon-small-left">
                                    <tr>
                                      <td class="x-btn-tl"><i>&nbsp;</i></td>
                                      <td class="x-btn-tc"></td>
                                      <td class="x-btn-tr"><i>&nbsp;</i></td>
                                    </tr>
                                    <tr>
                                      <td class="x-btn-ml"><i>&nbsp;</i></td>
                                      <td class="x-btn-mc"><em class=" x-unselectable" unselectable="on">
                                          <button type="button" id="ext-gen182" class=" x-btn-text">Зарегистрироваться
                                          </button>
                                        </em></td>
                                      <td class="x-btn-mr"><i>&nbsp;</i></td>
                                    </tr>
                                    <tr>
                                      <td class="x-btn-bl"><i>&nbsp;</i></td>
                                      <td class="x-btn-bc"></td>
                                      <td class="x-btn-br"><i>&nbsp;</i></td>
                                    </tr>
                                    </tbody>
                                  </table>
                                </div>
                                <div id="ext-comp-1051" style="float: right; position: initial;">
                                  <div id="ext-comp-1052" class=" x-panel x-panel-noborder"
                                       style="padding-top: 10px; padding-right: 10px;">
                                    <div class="x-panel-bwrap" id="ext-gen183">
                                      <div class="x-panel-body x-panel-body-noheader x-panel-body-noborder"
                                           id="ext-gen184" style="background: rgb(223, 232, 245);"><img
                                          src="/ico/loginForm/ico1.png" width="26px" height="26px"></div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="ext-el-mask" id="ext-gen234"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="ext-el-mask" id="ext-gen367" style="display: <?= isset($this->success) ? 'block' : 'none'?>;"></div>
<div id="ext-comp-1085" class="x-window x-window-plain x-window-dlg"
     style="visibility: <?= isset($this->success) ? 'visible' : 'hidden' ?>; /*left: 50%; top: 50%; transform: translate(-50%, -50%);*/">
  <div class="x-window-tl">
    <div class="x-window-tr">
      <div class="x-window-tc">
        <div class="x-window-header x-unselectable x-window-draggable" id="ext-gen359">
          <div class="x-tool x-tool-close" onClick="hideWindow()" id="ext-gen365" style="display: block;">&nbsp;</div>
          <span class="x-window-header-text" id="ext-gen371"><?= $this->success === true ? 'Информация' : 'Ошибка'?></span></div>
      </div>
    </div>
  </div>
  <div class="x-window-bwrap" id="ext-gen360">
    <div class="x-window-ml">
      <div class="x-window-mr">
        <div class="x-window-mc" id="ext-gen364">
          <div class="x-window-body" id="ext-gen361" style="width: 368px; height: auto;">
            <div id="ext-gen381">
              <div class="ext-mb-icon x-hidden" id="ext-gen382"></div>
              <div class="ext-mb-content"><span class="ext-mb-text" id="ext-gen383"><?= isset($this->success) && $this->success === true ? 'Авторизация прошла успешно. Перейдите в telegram.' : $this->message?></span><br>
                <div class="ext-mb-fix-cursor"><input type="text" class="ext-mb-input" id="ext-gen384"
                                                      style="display: none;"><textarea class="ext-mb-textarea"
                                                                                       id="ext-gen385"
                                                                                       style="display: none;"></textarea>
                </div>
              </div>
              <div class="x-progress-wrap x-hide-display" id="ext-comp-1086">
                <div class="x-progress-inner">
                  <div class="x-progress-bar" id="ext-gen387" style="height: 16px; width: 0px;">
                    <div class="x-progress-text x-hidden" id="ext-gen388" style="z-index: 99; width: 0px;">
                      <div id="ext-gen390" style="width: 382px; height: 18px;">&nbsp;</div>
                    </div>
                  </div>
                  <div class="x-progress-text x-progress-text-back" id="ext-gen389">
                    <div id="ext-gen391" style="width: 382px; height: 18px;">&nbsp;</div>
                  </div>
                </div>
              </div>
              <div class="x-clear" id="ext-gen392"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="x-window-bl" id="ext-gen363">
      <div class="x-window-br">
        <div class="x-window-bc">
          <div class="x-window-footer x-panel-btns" id="ext-gen362" style="width: 388px;">
            <div id="ext-comp-1084" class="x-panel-fbar x-small-editor x-toolbar-layout-ct" style="width: auto;">
              <table cellspacing="0" class="x-toolbar-ct">
                <tbody>
                <tr>
                  <td class="x-toolbar-left" align="center">
                    <table cellspacing="0">
                      <tbody>
                      <tr class="x-toolbar-left-row">
                        <td class="x-toolbar-cell" id="ext-gen372">
                          <table id="ext-comp-1080" cellspacing="0" class="x-btn x-btn-noicon" style="width: 75px;">
                            <tbody class="x-btn-small x-btn-icon-small-left">
                            <tr>
                              <td class="x-btn-tl"><i>&nbsp;</i></td>
                              <td class="x-btn-tc"></td>
                              <td class="x-btn-tr"><i>&nbsp;</i></td>
                            </tr>
                            <tr>
                              <td class="x-btn-ml"><i>&nbsp;</i></td>
                              <td class="x-btn-mc" onClick="hideWindow()"><em class=" x-unselectable" unselectable="on">
                                  <button type="button" id="ext-gen373" class=" x-btn-text">
                                  ОК</button>
                                </em>
                              </td>
                              <td class="x-btn-mr"><i>&nbsp;</i></td>
                            </tr>
                            <tr>
                              <td class="x-btn-bl"><i>&nbsp;</i></td>
                              <td class="x-btn-bc"></td>
                              <td class="x-btn-br"><i>&nbsp;</i></td>
                            </tr>
                            </tbody>
                          </table>
                        </td>
                        <td class="x-toolbar-cell x-hide-offsets" id="ext-gen374">
                          <table id="ext-comp-1081" cellspacing="0" class="x-btn  x-btn-noicon" style="width: 75px;">
                            <tbody class="x-btn-small x-btn-icon-small-left">
                            <tr>
                              <td class="x-btn-tl"><i>&nbsp;</i></td>
                              <td class="x-btn-tc"></td>
                              <td class="x-btn-tr"><i>&nbsp;</i></td>
                            </tr>
                            <tr>
                              <td class="x-btn-ml"><i>&nbsp;</i></td>
                              <td class="x-btn-mc"><em class=" x-unselectable" unselectable="on">
                                  <button type="button" id="ext-gen375" class=" x-btn-text">Да</button>
                                </em></td>
                              <td class="x-btn-mr"><i>&nbsp;</i></td>
                            </tr>
                            <tr>
                              <td class="x-btn-bl"><i>&nbsp;</i></td>
                              <td class="x-btn-bc"></td>
                              <td class="x-btn-br"><i>&nbsp;</i></td>
                            </tr>
                            </tbody>
                          </table>
                        </td>
                        <td class="x-toolbar-cell x-hide-offsets" id="ext-gen376">
                          <table id="ext-comp-1082" cellspacing="0" class="x-btn  x-btn-noicon" style="width: 75px;">
                            <tbody class="x-btn-small x-btn-icon-small-left">
                            <tr>
                              <td class="x-btn-tl"><i>&nbsp;</i></td>
                              <td class="x-btn-tc"></td>
                              <td class="x-btn-tr"><i>&nbsp;</i></td>
                            </tr>
                            <tr>
                              <td class="x-btn-ml"><i>&nbsp;</i></td>
                              <td class="x-btn-mc"><em class=" x-unselectable" unselectable="on">
                                  <button type="button" id="ext-gen377" class=" x-btn-text">Нет</button>
                                </em></td>
                              <td class="x-btn-mr"><i>&nbsp;</i></td>
                            </tr>
                            <tr>
                              <td class="x-btn-bl"><i>&nbsp;</i></td>
                              <td class="x-btn-bc"></td>
                              <td class="x-btn-br"><i>&nbsp;</i></td>
                            </tr>
                            </tbody>
                          </table>
                        </td>
                        <td class="x-toolbar-cell x-hide-offsets" id="ext-gen378">
                          <table id="ext-comp-1083" cellspacing="0" class="x-btn  x-btn-noicon" style="width: 75px;">
                            <tbody class="x-btn-small x-btn-icon-small-left">
                            <tr>
                              <td class="x-btn-tl"><i>&nbsp;</i></td>
                              <td class="x-btn-tc"></td>
                              <td class="x-btn-tr"><i>&nbsp;</i></td>
                            </tr>
                            <tr>
                              <td class="x-btn-ml"><i>&nbsp;</i></td>
                              <td class="x-btn-mc"><em class=" x-unselectable" unselectable="on">
                                  <button type="button" id="ext-gen379" class=" x-btn-text">Отмена</button>
                                </em></td>
                              <td class="x-btn-mr"><i>&nbsp;</i></td>
                            </tr>
                            <tr>
                              <td class="x-btn-bl"><i>&nbsp;</i></td>
                              <td class="x-btn-bc"></td>
                              <td class="x-btn-br"><i>&nbsp;</i></td>
                            </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                      </tbody>
                    </table>
                  </td>
                  <td class="x-toolbar-right" align="right">
                    <table cellspacing="0" class="x-toolbar-right-ct">
                      <tbody>
                      <tr>
                        <td>
                          <table cellspacing="0">
                            <tbody>
                            <tr class="x-toolbar-right-row"></tr>
                            </tbody>
                          </table>
                        </td>
                        <td>
                          <table cellspacing="0">
                            <tbody>
                            <tr class="x-toolbar-extras-row"></tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                </tbody>
              </table>
            </div>
            <div class="x-clear" id="ext-gen367"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <a href="#" class="x-dlg-focus" tabindex="-1" id="ext-gen368">&nbsp;</a></div>

<link href="/css/ext/ext-all-notheme.css" media="screen" rel="stylesheet" type="text/css" >
<link href="/css/telebot/main.css" media="screen" rel="stylesheet" type="text/css" >
<link href="/css/ext/xtheme-blue.css" media="screen" rel="stylesheet" type="text/css" >
<link href="/css/main.css" media="screen" rel="stylesheet" type="text/css" >

<script>
  function hideWindow() {
    var errorForm = document.getElementById('ext-comp-1085');
    var mask = document.getElementById('ext-gen367');
    var shadow = document.getElementById('ext-gen390');
    errorForm.style.visibility = 'hidden';
    mask.style.display = 'none';
    shadow.style.display = 'none';
  }
</script>